services:

  backend:
    container_name: chimera_backend
    build: .
    restart: unless-stopped
    ports:
      - "${BACKEND_LISTEN_PORT:-9090}:9090"

    healthcheck:
      test: ["CMD", "/backend/src/scripts/healthcheck.sh"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      
    networks:
      - backend_network

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
    
    networks:
      - backend_network

    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend_network
    volumes:
      - redisdata:/data

networks:
  backend_network:

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local