services:

  backend:
    volumes:
      - ./src/:/backend/src #monta o src do host dentro do backend do container

    command: ["/backend/src/scripts/dev.sh"]

  postgres:
    ports:
      - "5432:5432"
 
  redis:
    ports:
      - "6379:6379"