services:

  backend:
    develop:
      watch:
        # sincroniza todo o src para dentro do container
        - action: sync
          path: ./src
          target: /backend/src
          #ignore:
          #  - "src/app/"                  # ignora todo o diretório src/app
          #  - "src/app/**"               # garante recursão

        #reinicia o container se alguma config mudar
        - action: sync+restart
          path: ./src/config.py
          target: /backend/src/config.py

          # reinicia o container se o main mudar
        - action: sync+restart
          path: ./src/main.py
          target: /backend/src/main.py

        - action: sync+restart
          path: ./src/scripts
          target: /backend/src/scripts

        - action: rebuild
          path: ./pyproject.toml
          target: /backend/pyproject.toml

        - action: rebuild
          path: ./.env.dev
          
        - action: rebuild
          path: ./.env

        - action: rebuild
          path: ./Dockerfile

    command: ["/backend/src/scripts/watch.sh"]

  postgres:
    ports:
      - "5432:5432"
 
  redis:
    ports:
      - "6379:6379"